import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-center text-5xl mt-[5rem]">
          Hello World 🚀
        </h1>
      </main>
    </div>
  )
}
