import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.target);
    const dataObj = Object.fromEntries(data);
    setLoading(true);

    const response = await fetch("/api/getStory", {
      method: "POST",
      body: JSON.stringify({ prompt: dataObj.prompt,genre:dataObj.genre }), 
      headers: {
        "Content-Type": "application/json",
      },
    });
    const result = await response.json();
    setData(result);
    setLoading(false);
  };

  return (
    <div className="">
      <Head>
        <title>Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className="text-center text-2xl md:text-4xl mt-[5rem]">
          Get Short Story 📖
        </h1>

        <form onSubmit={handleSubmit} className="my-5 text-center">
          <input
            type="text"
            className="text-center text-sm md:text-2xl py-4 px-2 md:px-8 mt-10 mb-5 mx-2 md:mx-5"
            name="prompt"
            required
            placeholder="Alien Invasion on Earth"
          />
          <select name="genre" id="genre" className="text-xl py-2 px-2 text-center">
            <option value="Horror">Horror</option>
            <option value="Adventurous">Adventurous</option>
            <option value="drama">Drama</option>
            <option value="Romance">Romance</option>
            <option value="Fairy Tale">Fairy Tale</option>  
            <option value="Fantasy">Fantasy</option>
            <option value="Motivation">Motivation</option>
            <option value="Comedy">Comedy</option>
            <option value="Fiction">Fiction</option>
          </select>
          <br />
          <button
            type="submit"
            className="my-5 bg-white text-black py-3 px-7 sm:text-xl rounded-full font-bold border-2 border-white hover:bg-black hover:text-white text-sm"
          >
            Submit
          </button>
        </form>
        {loading && (
          <p className="text-center my-5 10">Generating a story...</p>
        )}
        <div className="text-center mb-5 mt-[2rem] md:mt-[4rem] mx-[1rem] md:mx-[10rem] ">{data}</div>
    </div> 
  );
}
